### ISSUE TITLE
documentation and use cases

### ISSUE THREAD

**Issue by lecy** [hrecht/censusapi#1]
Hi Hannah - 

Great wrapper functions for the Census API. These are very useful!

Have you started documentation on some of the common variables and geographies through example use cases, data dictionaries, or vignettes? Is this something that you could use help with?

Jesse

**Comment by hrecht** [comment]
Thanks Jesse! I haven't had time to focus on this package in recent months, but am hoping to turn back to it in early 2017. Documentation is absolutely an area that I'd like to build up, but plan to make some function improvements first.
In the meantime, there's a great walkthrough here: http://www.computerworld.com/article/3120415/data-analytics/how-to-download-new-census-data-with-r.html
Are there any specific topics that you'd like to see documented in the next version?

**Comment by lecy** [comment]
Yes, just a basic catalog of the "usual suspect" social and economic variables. It's so hard to look these up in census documents.

I was partly asking because I'm happy to help out if you don't have something like this already!

This message was sent from a mobile device.

**Comment by hrecht** [comment]
Got it, thanks. I think that would be out of scope for this R package, since it isn't specific to any one API (e.g. ACS or decennial Census) but is a general accessor for the suite of Census APIs. But I think a catalog like that would be quite useful if you want to write it for general public use.

**Comment by hrecht** [comment]
@lecy also recommend you talk to Amelia McNamara (https://twitter.com/AmeliaMN) about this - she's been exploring the same issue.

**Comment by lecy** [comment]
Yep, happy to contribute. I just wanted to make sure there was not
something in the works first. Let me know if we can create it in any way
that would be helpful to you.

I'll check with Amelia.

Thanks!



*Jesse Lecy*
Assistant Professor • Syracuse
*T:* +1 315 443 2252 / *M:* +1 801 462 1648
jdlecy@syr.edu / www.maxwell.syr.edu  <http://www.maxwell.syr.edu/>

**Comment by hrecht** [comment]
Look forward to seeing what you come up with. Closing this issue since it won't be a censusapi task. Thanks!
