### ISSUE TITLE
Siscuss differences to acs package in docs

### ISSUE THREAD

**Issue by RoyalTS** [hrecht/censusapi#16]
Would be good for people to get an idea of what the advantages/disadvantages of using the two packages are.

**Comment by hrecht** [comment]
I'm not very familiar with the latest versions of acs, but the main difference is that `acs` allows retrieval of data from the American Community Survey and Decennial Census APIs. `censusapi` accesses those APIs as well as the other Census APIs. 

Other differences include how the arguments are specified and how data is returned. Generally, this package uses the same parameter names as the Census APIs themselves and returns data frames. 

I think advantage/disadvantage depends on the user's preferences and goals, and what datasets they want to use. For that reason, I don't plan to directly compare/contrast this package with other Census wrappers like `acs` or `tidycensus` in the documentation at this time. I'm not familiar enough with `acs` to answer specific syntax comparison questions, etc but if you have general questions about this package I can certainly answer those or expand in the documentation.
