### ISSUE TITLE
Switch to HTTPS requests

### ISSUE THREAD

**Issue by hrecht** [hrecht/censusapi#18]
Census APIs are moving to https-only on August 28

**Comment by bbrewington** [comment]
In case it helps -
 https://content.govdelivery.com/attachments/USCENSUS/2017/05/31/file_attachments/824523/HttpsChangeDocument.pdf

**Comment by hrecht** [comment]
Yep, thanks @bbrewington! This change should be live within a day or so.

**Comment by hrecht** [comment]
Closed with https://github.com/hrecht/censusapi/commit/242efd5e2016be4bc9e250b7c49cb61aac0d0d35
