### ISSUE TITLE
Returning a single block throws error.

### ISSUE THREAD

**Issue by jhollist** [hrecht/censusapi#23]
Gist with details:  https://gist.github.com/jhollist/010bdbb78c1cf5ce1a55ae4dd6830879

**Comment by hrecht** [comment]
Thanks, this appears to be an issue for single-row responses generally. Also fails with other geographic specs and API endpoints. Will fix.

`getCensus(name = "sf1",vintage = 2010, vars = "P0010001", region = "state:1")`
`getCensus(name="acs5", vintage=2014,vars=c("NAME", "B01001_001E"), region="state:1")`

**Comment by jhollist** [comment]
Awesome, thanks!

**Comment by hrecht** [comment]
@jhollist Did you notice this error before updating to v0.1.1? Trying to figure out if recent changes introduced it or if it's an older bug.

**Comment by jhollist** [comment]
Today is my first time using censusapi!  So v0.1.1 is all I've seen.
