### ISSUE TITLE
pep apis connection error

### ISSUE THREAD

**Issue by psantossilva** [hrecht/censusapi#30]
For most of the apis I can get the list of variables, geography, etc. However, for "pep" apis I get a connection error. 

listCensusMetadata(name="pep/subcty", type = "variables")
Error in open.connection(con, "rb") : HTTP error 404

Is there a way of fixing this?

Thank you!

**Comment by hrecht** [comment]
Just seeing this now, it looks like you found a solution?

**Comment by psantossilva** [comment]
I did. Unfortunately I can't delete the thread.
But Thank you,

Karina Thomas
