### ISSUE TITLE
Quarterly Workforce Indicator categorical parameters

### ISSUE THREAD

**Issue by hrecht** [hrecht/censusapi#40]
The [QWI API](https://www.census.gov/data/developers/data-sets/qwi.html) allows a lot of different specifications that are not currently supported in `censusapi`, though [basic calls](https://hrecht.github.io/censusapi/articles/example-masterlist.html#quarterly-workforce-indicators) do work in `censusapi`. 

Supporting complicated calls would be a future priority.

**Comment by aeonstone** [comment]
Hi @hrecht Just wanted to chime is saying I can definitely understand how this one way messier than the other APIs, but I hope you can tackle it some day. My own use case is wanting to pull down data for certain industries. Maybe just employment counts for industry == XXXX, for example. Maybe that would be a good intermediate step, if I can make a selfish suggestion.

You're awesome and I love this library! Keep up the great work.

**Comment by hrecht** [comment]
Done in v0.6.0, which adds the ability to use miscellaneous paramaters. It's not on CRAN yet, but can be installed with:
```
# install.packages("devtools")
devtools::install_github("hrecht/censusapi")
```

Here's an example:
```R
qwi <- getCensus(name = "timeseries/qwi/sa",
region = "state:02",
vars = c("Emp", "sex"),
year = 2012,
quarter = 1,
agegrp = "A07",
ownercode = "A05",
seasonadj = "U",
industry = 21)
```
