### ISSUE TITLE
Add ability to include miscellaneous parameters

### ISSUE THREAD

**Issue by RSchwinn** [hrecht/censusapi#49]
Thanks for your great package!
Would it be possible to add miscellaneous parameters to API requests? The county business patterns requires additional comments in order to report data by employment size. See example below:

- No Employment Sizes
`https://api.census.gov/data/2008/cbp?get=YEAR,EMPSZES_TTL,EMP,ESTAB,PAYANN,GEO_TTL&for=state:01`

- Adding "&EMPSZES=*" Provides Employment Sizes
`https://api.census.gov/data/2008/cbp?get=YEAR,EMPSZES_TTL,EMP,ESTAB,PAYANN,GEO_TTL&for=state:01&EMPSZES=*`

**Comment by hrecht** [comment]
Yes, hoping to add that in the next version of this package!

**Comment by hrecht** [comment]
Done, in https://github.com/hrecht/censusapi/commit/a5f0edb8081c428e7ae092065b3c39a408f3869d

Here's an example using EMPSZES:
```
cbp_2008 <- getCensus(name = "cbp",
  vintage = 2008,
  vars = c("YEAR", "EMPSZES_TTL", "EMP", "ESTAB", "PAYANN", "GEO_TTL"),
  region = "state:*",
  EMPSZES = 260)
head(cbp_2008)
```
