### ISSUE TITLE
Add instructions for manually adding key to Renviron

### ISSUE THREAD

**Issue by hrecht** [hrecht/censusapi#59]
A few users lately have reported issues saving to their root .Renviron file, for unclear reasons probably relating to R install location (not related to this package). Add a backup instruction for Mac users to manually open the file from the terminal and paste the key in that way.
Find out how to do that on PCs too.

**Comment by chill-fpraz** [comment]
I found this [stackoverflow](https://stackoverflow.com/a/59277150) comment which had the path to the Renviron file for macs: /Library/Frameworks/R.framework/Versions/Current/Resources/etc/

**Comment by hrecht** [comment]
This issue was related to general Renviron and file path issues - I haven't heard any concerns about this recently so I'm closing. If it pops again we can reopen.

**Comment by hrecht** [comment]
This issue was related to general Renviron and file path issues - I haven't heard any concerns about this recently so I'm closing. If it pops again we can reopen.

**Comment by hrecht** [comment]
Closing

**Comment by hrecht** [comment]
trying to correctly categorize!

**Comment by hrecht** [comment]
trying to correctly categorize!

**Comment by hrecht** [comment]
Close as stale

**Comment by hrecht** [comment]
Close as stale

**Comment by hrecht** [comment]
Closing

**Comment by hrecht** [comment]
Well "close as not planned" isn't working - that will be a nice option when it's out of beta.

**Comment by hrecht** [comment]
Well "close as not planned" isn't working - that will be a nice option when it's out of beta.

**Comment by hrecht** [comment]
Well "close as not planned" isn't working - that will be a nice option when it's out of beta.
