### ISSUE TITLE
Rapidly Gathering Block Data

### ISSUE THREAD

**Issue by braedenmc1** [hrecht/censusapi#71]
**Describe the bug**
I am trying to manipulate the example of gathering block data in the README, but apply it to collecting data from the 2000 Decennial Census as a whole. I'm not sure I'm on the right track, but I will post the code below

**To Reproduce**
```
data2000 <- getCensus(
  key = Sys.getenv("census_key"),
  name = "dec/sf1",
  vintage = 2000,
  vars = "P001001", 
  region = "block:*",
  regionin = "state: + county: + tract:")
```

**Expected behavior**
I was hoping that linking the region measures together would pull data for the entire US, but I get a long error code.

**R session information:**
 - censusapi package version: 0.7.1
 - R version: 4.0.2

**Additional context**
My goal is to gather information on the Latino population at the block level, but I wanted to reproduce the example to collect data from all the blocks before adding the variable I want to explore.

**Comment by hrecht** [comment]
Unfortunately `regionin = "state: + county: + tract:"` is not valid code. You need to put actual fips codes there. You can do that in a for loop, like here: https://hrecht.github.io/censusapi/articles/getting-started.html#advanced-geographies

You'd need to loop over all combinations. Using bulk data from the Census or NHGIS might make more sense than looping over all tracts with the API. It's a shame they don't allow a simple call to get that data.

**Comment by hrecht** [comment]
Deleted a previous reply - Census actually seems to have made this easier recently!
`regionin = "state: + county: + tract:"` is not valid code, you need to use fips codes and/or wildcards. You need to specify state here but can use wildcards for county and tract (to get every block in a single state in one call.)

You can do this in a for loop like the example here. https://hrecht.github.io/censusapi/articles/getting-started.html#advanced-geographies

```R
blocks <- NULL
for (f in fips) {
	stateget <- paste("state:", f, "+county:*+tract:*", sep="")
	print(f)
	temp <- getCensus(
		name = "dec/sf1",
		vintage = 2000,
		vars = "P001001",
		region = "block:*",
		regionin = stateget)
	blocks <- rbind(blocks, temp)
}
```

Note: this will take a while to run. Unless you really really need block-level data I'd recommend block group or tract. Not much detailed data is available at the block level. You could also download bulk data from NHGIS.

**Comment by braedenmc1** [comment]
Thank you for the help! I just realized I need block-group data. My apologies for sending you in the wrong direction. Would the best approach still be using the function you posted in your response for the block group data? If not, is there another approach you would recommend? This is my first time using data at this level, so I am still getting the terminology straight.

Another quick follow up question:

I am also looking for the same variable for state-level House districts (not Congressional districts. Would this data be found in the ``` "dec/sldhprofile"``` API or does the ```sec/sf1``` API contain information on this level of analysis as well?

**Comment by braedenmc1** [comment]
Hello!

I have the specific code I want to return from the 2000 Decennial state legislative file.

```
#Get Latino District Population
leg_test <- getCensus(
  key = Sys.getenv("census_key"),
  name = "dec/sldhprofile",
  vintage = 2000, 
  vars = "DP1_C100",
  region = "state", 
  regionin = "state legislative district (lower chamber)")
```

I read the variables from this API after manipulating the ```listCensusMetadata``` argument for this particular API. The lower state house district required the state argument to run, but after adding the region and region in arguments the way the variables appeared in the API, I still received an error.

**Comment by hrecht** [comment]
You need to specify the region and regionin arguments, in your case with the wildcard. So `region = "state:*"` etc. Here's an intro article that should help: https://hrecht.github.io/censusapi/articles/getting-started.html
