### ISSUE TITLE
Bug report: Values returning NA

### ISSUE THREAD

**Issue by dcmg21** [hrecht/censusapi#78]
**Describe the bug**
For some reason certain variable numbers only return NA values.  I could be doing something wrong but for the most part I'm able to retrive the Total Numbers of data but when I attempt to get lower values that add up to the total I only get NA's.

**To Reproduce**
getCensus(name = "acs/acs1", vintage = "2019", key = Sys.getenv("CENSUS_KEY"), vars = "B02003_009E", region = "state")

**Expected behavior**

**R session information:**
 - censusapi package version: 0.7.1
 - R version: 4.1.2

**Additional context**

**Comment by hrecht** [comment]
Hello, those NA values are coming from the API response itself, not the R package. If you use the option `show_call = T` you'll see that there are nulls in the underlying response at https://api.census.gov/data/2019/acs/acs1?get=B02003_009E&for=state%3A* 
Please reach out to the Census Bureau staff via email or slack for help on that variable. https://join.slack.com/t/uscensusbureau/shared_invite/zt-optzh7xs-ApNgf5Yqbo_u2ANXQv67cQ

**Comment by hrecht** [comment]
Digging a little more...all of these detailed race variables are null on the state level. It's possible they may be available at the national level only, but the Census staff should be able to answer that question. https://api.census.gov/data/2019/acs/acs1?get=group(B02003)&for=state:*
