### ISSUE TITLE
Feature request: ability to connect via proxy: like the use_proxy() function in the httr::GET

### ISSUE THREAD

**Issue by lcarmoega** [hrecht/censusapi#81]
Normally I would connect to the API via httr::GET, pass the API URL, and use the use_proxy() function. I was wondering if there is a way, or if it can be implemented into the library to do that as well.

Thanks,

Luis

**Comment by hrecht** [comment]
You can set global proxy settings in your R config, implementing it into this library would be out of scope especially since last I checked use_proxy() was not ported over to httr2. Eventually this package may upgrade to httr2 dependency and so that would break anyway.
