### ISSUE TITLE
Bug report: CPS Basic variable names

### ISSUE THREAD

**Issue by matiasds** [hrecht/censusapi#84]
**Describe the bug**
I'm not able to get the variable names of CPS basic monthly datasets.

**To Reproduce**
cps_vars <- listCensusMetadata(
  name = "cps/basic/jan",
  vintage = 2022,
  type = "variables")

**Expected behavior**
I expected to get the variable names of the CPS basic monthly data sets. I instead get the following error message: 
"Error in rbind(deparse.level, ...) : 
  numbers of columns of arguments do not match

**R session information:**
 - censusapi package version: 0.7.1
 - R version: 4.1.2

**Additional context**

**Comment by hrecht** [comment]
Hello, is this for the microdata APIs https://www.census.gov/data/developers/data-sets/census-microdata-api.CPS.html ?
If so, they're structured pretty differently than the summary data APIs. Your best bet for the microdata would be to use tidycensus, which has functions for those endpoints, or to use IPUMS which has nicely cleaned data and an R package.
Let me know if I'm misunderstanding.

**Comment by hrecht** [comment]
Hello @matiasds  - the new developement version of censusapi, 0.8.0, should fix this. It turns out the Census Bureau was using invalid json key-value pair names in the CPS metadata, which caused this error. It's now working on my end - could you try again using the latest version? You can get that using the `devtools` package:

```R
# install.packages("devtools")
devtools::install_github("hrecht/censusapi")
```

**Comment by hrecht** [comment]
Reopening pending further testing to make sure there aren't other invalid characters in the new API endpoints.

**Comment by matiasds** [comment]
Thank you so much, @hrecht. And sorry for the late reply. I'm relatively new to GitHub.

**Comment by hrecht** [comment]
No worries! Thanks for flagging the issue.
