### ISSUE TITLE
Feature request: Make API key optional

### ISSUE THREAD

**Issue by szimmer** [hrecht/censusapi#87]
**Is your feature request related to a problem? Please describe.**
Census now allows calls without an API key. Allow users to not specify API key at all. Very useful to use package in a GitHub repository with actions and not storing a secret key.

**Describe the solution you'd like**
Allow NULL to be specified for key in the `getCensus` function.

**Describe alternatives you've considered**
Store secret API keys in a GitHub repo.

**Additional context**
Pull request coming for this.

**Comment by hrecht** [comment]
Adding this to the queue to explore for the next sprint, likely in January. Thanks for suggesting!

**Comment by hrecht** [comment]
Closed with https://github.com/hrecht/censusapi/commit/d8254f09a0054b9d5610a6c3d2e15a42eec89fc1
