### ISSUE TITLE
Install fails due to problem with DESCRIPTION file

### ISSUE THREAD

**Issue by mtreg** [hrecht/censusapi#9]
Looks like when the e-mail address was removed from the DESCRIPTION, that causes an error during install tests. Relevant output is below: 

    * installing *source* package 'censusapi' ...
    Error : Invalid DESCRIPTION file
    
    Authors@R field gives no person with maintainer role, valid email
    address and non-empty name.
    
    See section 'The DESCRIPTION file' in the 'Writing R Extensions'
    manual.
    
    ERROR: installing package DESCRIPTION failed for package 'censusapi'

**Comment by hrecht** [comment]
Oops, fixed with https://github.com/hrecht/censusapi/commit/c0b335cda0c241dc21e0c5caac8cfbd3fe89ac83
Can you try again and let me know if you're still getting the error?

**Comment by mtreg** [comment]
Works again - thanks!
